#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Leopard\Doctrine\EntityManager as CoreEntityManager;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;
use Doctrine\ORM\Tools\Console\ConsoleRunner;

global $container;

$application = new Application($container->get('params')->get('app.name'), $container->get('params')->get('app.version'));
$entityManagerProvider = new SingleManagerProvider(CoreEntityManager::getEntityManager());

// Automatically load all commands from the src/Commands directory
$commandsPath = __DIR__ . '/src/Commands';
foreach (scandir($commandsPath) as $file) {
    if (is_file($commandsPath . '/' . $file) && preg_match('/Command\.php$/', $file)) {
        $className = 'App\\Commands\\' . pathinfo($file, PATHINFO_FILENAME);
        if (class_exists($className)) {
            $reflection = new ReflectionClass($className);
            if (!$reflection->isAbstract()) {
                $application->add(new $className());
            }
        }
    }
}

$commands = ConsoleRunner::createApplication($entityManagerProvider)->all();

foreach ($commands as $command) {
    $application->add($command);
}

$application->run();
