routes:
  - path: /custom-route
    method: GET
    controller: HomeController
    action: customMethod

controllers:
  - controller: HomeController
    path: /

  - namespace: Admin
    path: /admin

  - namespace: Api
    path: /api
